# Site settings
title: "GreenFit AI - Product Showcase"
email: "greenfitai.team@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  "Find out about sustainability in your favorite sport clothing brands, in just one click!"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://greenfitai.org" # the base hostname & protocol for your site

twitter_username: starrynightdev
github_username: greenfit-ai

# Build settings
markdown: kramdown
